/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package BACKAPp;
import java.io.IOException;

import BACKAPp.model.Model;
import BACKAPp.presenter.BackupPresenter;
import BACKAPp.presenter.InputDatePresenter;
import BACKAPp.presenter.InputPathPresenter;
import BACKAPp.presenter.PathTimePresenter;
import BACKAPp.view.BackupView;
import BACKAPp.view.InputDate;
import BACKAPp.view.InputPath;
import BACKAPp.view.PathTimeView;
import javafx.application.Application;
import javafx.geometry.Insets;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.layout.Background;
import javafx.scene.layout.BackgroundFill;
import javafx.scene.layout.CornerRadii;
import javafx.scene.layout.GridPane;
import javafx.scene.paint.Color;
import javafx.stage.Stage; 

public class App extends Application{

    public static void main(String[] args) {
        launch(args);
    }

    @Override
  public void start(Stage primaryStage) {

    primaryStage.setTitle("Carnival Mask Pairs");

    InputPath input = new InputPath();

    PathTimeView pt = new PathTimeView();
    InputDate id = new InputDate();
    BackupView display1 = new BackupView(3, "Ultimi Backup");


    GridPane gridPane = new GridPane();
    gridPane.setBackground(new Background(new BackgroundFill(Color.DARKGRAY, CornerRadii.EMPTY, Insets.EMPTY)));

    
    gridPane.setPadding(new Insets(10, 10, 10, 10));
    
    gridPane.add(input, 0, 0);
    GridPane.setColumnSpan(input, 3);

    gridPane.setPadding(new Insets(10, 10, 10, 10));
    gridPane.add(id, 1, 0);

    gridPane.setPadding(new Insets(10, 10, 10, 10));
    gridPane.add(pt, 0, 1);
    
    gridPane.setPadding(new Insets(10, 10, 10, 10));
    gridPane.add(display1, 1, 1);



    try {
      Model m = new Model("app/src/main/java/resources");
      /*************************************
       * SOLO QUANDO AVRAI FINITO TUTTI I SORGENTI PASSERAI ALL'INTEGRAZIONE DEI COMPONENTI,
       * POTRAI DUNQUE TOGLIERE I COMMENTI AL CODICE SOTTOSTANTE
       ****************************************/
      //BackupPresenter bp = new BackupPresenter(m, display1);
      //InputDatePresenter idp = new InputDatePresenter(m, id);
      //InputPathPresenter ipp = new InputPathPresenter(m, input);
      //PathTimePresenter ptp = new PathTimePresenter(m, pt);

      //m.notifyObservers();
    } catch (IOException e) {
      pt.showError("IMPOSSIBILE CARICARE FILE DI CONFIGURAZIONE");
    }

    Scene scene = new Scene(gridPane);
    primaryStage.setScene(scene);
    primaryStage.show();
  }
}
